server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #localhost #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
#      defaultZone: http://eureka7002.com:7002/eureka/ #集群就是指向其他eureka
      defaultZone: http://localhost:7001/eureka #单机就是自己
  server:
    enable-self-preservation: false  #默认是eureka的自我保护机制true，现在设置为false
    eviction-interval-timer-in-ms: 2000  #默认心跳时间90s，现在设置2s
